name: Publish

on:
  schedule:
    - cron:  '*/6 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denolib/setup-deno@v2.3.0
        with:
          deno-version: v1.x

      - name: Run lume
        run: |
          deno run -A https://deno.land/x/lume/ci.js
        env:
          API_KEY: ${{ secrets.API_KEY }}
          EVENT_ID: ${{ secrets.EVENT_ID }}

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
          SOURCE: "_site/"
          REMOTE_HOST: www.tarugoconf.com
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: ${{ secrets.SERVER_PATH }}
          EXCLUDE: "/dist/, /node_modules/"